### ISSUE TITLE
Feature request: <abbr> tag and small-caps support

### ISSUE THREAD

**Issue by blueset** [phpbits/block-options#182]
## `<abbr>` tag
Create inline abbreviations using `abbr` tag, and allow user to set the `title` attribute. UI can be similar to what _link_ tool is like.

e.g.:
```html
<abbr title="Cascade Style Sheet">CSS</abbr>
```

## Small caps
In addition to the ”uppercase” support in EditorsKit, it would be great to also have support to small caps, ideally both _small caps_ and _all small caps_.

CSS-wise, it can be achieved with property `font-variant-caps` (in CSS3), like:
```css
.editor-kit-small-caps {
    font-variant-caps: small-caps;
}
.editor-kit-all-small-caps {
    font-variant-caps: all-small-caps;
}
```
Alternatively property `font-variant` can be used in the same way for backward compatibility.
